# tab-cli configuration for this project
version: 1

# Base directory for worktrees
worktree_dir: "../worktrees"

# Project name (used for tmux session naming)
project_name: "tab-cli"

# Files to copy to new worktree
copy:
  - .vscode/
  - .claude/

# Commands to run after worktree creation
setup:
  - name: "Install dependencies"
    command: "bun install"

# IDE command
ide:
  command: "code $TAB_WORKTREE_DIR"

# Tmux session configuration
tmux:
  windows:
    - name: "claude"
      command: "claude"
    - name: "git"
      command: "lazygit"
    - name: "dev"
      split: "horizontal"
      panes:
        - command: "bun test --watch"
        - {}
