/** biome-ignore-all lint/suspicious/noTemplateCurlyInString: shell variable interpolation */

import { commandDef as cdCommandDef } from "../commands/cd";
import { commandDef as closeCommandDef } from "../commands/close";
import type { CommandDef } from "../commands/command-def";
import { commandDef as downCommandDef } from "../commands/down";
import { commandDef as hooksCommandDef } from "../commands/hooks";
import { commandDef as initCommandDef } from "../commands/init";
import { commandDef as listCommandDef } from "../commands/list";
import { commandDef as notifyCommandDef } from "../commands/notify";
import { commandDef as openCommandDef } from "../commands/open";
import { commandDef as projectsCommandDef } from "../commands/projects";
import { commandDef as switchCommandDef } from "../commands/switch";
import { commandDef as tuiCommandDef } from "../commands/tui";
import { commandDef as upCommandDef } from "../commands/up";

const COMMANDS: ReadonlyArray<CommandDef> = [
  cdCommandDef,
  closeCommandDef,
  downCommandDef,
  hooksCommandDef,
  initCommandDef,
  listCommandDef,
  notifyCommandDef,
  openCommandDef,
  projectsCommandDef,
  switchCommandDef,
  tuiCommandDef,
  upCommandDef,
];

const GLOBAL_LOG_LEVELS = [
  "all",
  "trace",
  "debug",
  "info",
  "warn",
  "warning",
  "error",
  "fatal",
  "none",
] as const;

function getAllNames(command: CommandDef): Array<string> {
  return [command.name, ...(command.aliases ?? [])];
}

function quoteFish(value: string): string {
  const escaped = value.replaceAll("\\", "\\\\").replaceAll("'", "\\'");
  return `'${escaped}'`;
}

function generateFishCompletions(): string {
  const lines: Array<string> = [
    "# Fish completions for wct",
    "# Generated by: wct --completions fish",
    "",
    "# Erase inherited completions (e.g. from alias --wraps)",
    "complete -c wct -e",
    "",
    "# Disable file completions by default",
    "complete -c wct -f",
    "",
    "# Helper: list git branches for completion",
    "function __wct_branches",
    "    git branch --format='%(refname:short)' 2>/dev/null",
    "end",
    "",
    "# Helper: list branches that have worktrees",
    "function __wct_worktree_branches",
    "    git worktree list --porcelain 2>/dev/null | string match -rg '^branch refs/heads/(.+)$'",
    "end",
    "",
    "# Helper: list config profile names",
    "function __wct_profiles",
    "    if test -f .wct.yaml",
    '        awk \'/^profiles:/{found=1;next} found && /^[^ ]/{exit} found && /^  [a-zA-Z]/{sub(/^  /,"");sub(/:.*/,"");print}\' .wct.yaml',
    "    end",
    "end",
    "",
    "# Commands",
  ];

  for (const command of COMMANDS) {
    for (const name of getAllNames(command)) {
      lines.push(
        `complete -c wct -n '__fish_use_subcommand' -a ${quoteFish(name)} -d ${quoteFish(command.description)}`,
      );
    }

    if (command.subcommands) {
      const subNames = command.subcommands.map((s) => s.name).join(" ");
      for (const sub of command.subcommands) {
        lines.push(
          `complete -c wct -n '__fish_seen_subcommand_from ${command.name}; and not __fish_seen_subcommand_from ${subNames}' -a ${quoteFish(sub.name)} -d ${quoteFish(sub.description)}`,
        );
      }
      for (const sub of command.subcommands) {
        for (const option of sub.options ?? []) {
          const parts = [
            "complete -c wct",
            `-n '__fish_seen_subcommand_from ${command.name}; and __fish_seen_subcommand_from ${sub.name}'`,
          ];
          if (option.short) {
            parts.push(`-s ${option.short}`);
          }
          parts.push(`-l ${option.name}`);
          if (option.type === "string") {
            parts.push("-r");
          }
          parts.push(`-d ${quoteFish(option.description)}`);
          if (option.completionValues) {
            parts.push(`-a '(${option.completionValues})'`);
          }
          lines.push(parts.join(" "));
        }

        if (sub.completionType === "path") {
          lines.push(
            `complete -c wct -n '__fish_seen_subcommand_from ${command.name}; and __fish_seen_subcommand_from ${sub.name}' -a '(__fish_complete_directories)' -d 'Path to repo'`,
          );
        }
      }
    }
  }

  lines.push("");
  lines.push("# Global options");
  lines.push(
    "complete -c wct -n '__fish_use_subcommand' -s h -l help -d 'Show help information'",
  );
  lines.push(
    "complete -c wct -n '__fish_use_subcommand' -l version -d 'Show version information'",
  );
  lines.push(
    "complete -c wct -n '__fish_use_subcommand' -l completions -r -f -a 'fish bash zsh sh' -d 'Print shell completion script'",
  );
  lines.push(
    `complete -c wct -n '__fish_use_subcommand' -l log-level -r -f -a '${GLOBAL_LOG_LEVELS.join(" ")}' -d 'Sets the minimum log level'`,
  );

  lines.push("");
  lines.push("# Per-command options");

  for (const command of COMMANDS) {
    if (!command.options) continue;
    const names = getAllNames(command);
    for (const option of command.options) {
      const parts = [
        "complete -c wct",
        `-n '__fish_seen_subcommand_from ${names.join(" ")}'`,
      ];
      if (option.short) {
        parts.push(`-s ${option.short}`);
      }
      parts.push(`-l ${option.name}`);
      if (option.type === "string") {
        parts.push("-r");
      }
      parts.push(`-d ${quoteFish(option.description)}`);
      if (option.completionValues) {
        parts.push(`-a '(${option.completionValues})'`);
      }
      lines.push(parts.join(" "));
    }
  }

  const branchCommands = COMMANDS.filter(
    (command) =>
      command.args?.includes("<branch>") &&
      command.completionType !== "worktree",
  )
    .flatMap((command) => getAllNames(command))
    .join(" ");

  const worktreeCommands = COMMANDS.filter(
    (command) => command.completionType === "worktree",
  )
    .flatMap((command) => getAllNames(command))
    .join(" ");

  if (branchCommands) {
    lines.push("");
    lines.push("# Branch completions");
    lines.push(
      `complete -c wct -n '__fish_seen_subcommand_from ${branchCommands}' -a '(__wct_branches)' -d 'Branch name'`,
    );
  }

  if (worktreeCommands) {
    lines.push("");
    lines.push("# Worktree branch completions");
    lines.push(
      `complete -c wct -n '__fish_seen_subcommand_from ${worktreeCommands}' -a '(__wct_worktree_branches)' -d 'Branch name'`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

function generateBashCompletions(): string {
  const commandNames = COMMANDS.flatMap((command) => getAllNames(command)).join(
    " ",
  );
  const globalFlags = "--help --version --completions --log-level";
  const branchCommands = COMMANDS.filter(
    (command) =>
      command.args?.includes("<branch>") &&
      command.completionType !== "worktree",
  ).flatMap((command) => getAllNames(command));
  const worktreeCommands = COMMANDS.filter(
    (command) => command.completionType === "worktree",
  ).flatMap((command) => getAllNames(command));

  const lines: Array<string> = [
    "# Bash completions for wct",
    "# Generated by: wct --completions bash",
    "",
    "_wct_branches() {",
    "    git branch --format='%(refname:short)' 2>/dev/null",
    "}",
    "",
    "_wct_worktree_branches() {",
    "    git worktree list --porcelain 2>/dev/null | sed -n 's|^branch refs/heads/||p'",
    "}",
    "",
    "_wct_profiles() {",
    "    if [[ -f .wct.yaml ]]; then",
    '        awk \'/^profiles:/{found=1;next} found && /^[^ ]/{exit} found && /^  [a-zA-Z]/{sub(/^  /,"");sub(/:.*/,"");print}\' .wct.yaml',
    "    fi",
    "}",
    "",
    "_wct() {",
    '    local cur="${COMP_WORDS[COMP_CWORD]}"',
    '    local prev="${COMP_WORDS[COMP_CWORD-1]}"',
    '    local cword="$COMP_CWORD"',
    "",
    "    if [[ $cword -eq 1 ]]; then",
    `        COMPREPLY=($(compgen -W '${commandNames}' -- "$cur"))`,
    "        return",
    "    fi",
    "",
    '    local cmd="${COMP_WORDS[1]}"',
    '    case "$cmd" in',
  ];

  for (const command of COMMANDS) {
    if (command.subcommands) continue;
    const options: Array<string> = [];
    if (command.options) {
      for (const option of command.options) {
        options.push(`--${option.name}`);
        if (option.short) {
          options.push(`-${option.short}`);
        }
      }
    }
    const allNames = getAllNames(command);
    const isBranchCommand = allNames.some((name) =>
      branchCommands.includes(name),
    );
    const isWorktreeCommand = allNames.some((name) =>
      worktreeCommands.includes(name),
    );
    const completionFunction = isWorktreeCommand
      ? "_wct_worktree_branches"
      : "_wct_branches";

    lines.push(`        ${allNames.join("|")})`);
    const optionsWithCompletionValues = (command.options ?? []).filter(
      (option) => option.completionValues,
    );
    for (const option of optionsWithCompletionValues) {
      const prevCheck = option.short
        ? `"$prev" == "--${option.name}" || "$prev" == "-${option.short}"`
        : `"$prev" == "--${option.name}"`;
      const bashFunc = option.completionValues
        ? option.completionValues.replace(/^__/, "_")
        : option.completionValues;
      lines.push(`            if [[ ${prevCheck} ]]; then`);
      lines.push(
        `                COMPREPLY=($(compgen -W "$(${bashFunc})" -- "$cur"))`,
      );
      lines.push("                return");
      lines.push("            fi");
    }
    if (options.length > 0) {
      lines.push(
        `            COMPREPLY=($(compgen -W '${globalFlags} ${options.join(" ")}' -- "$cur"))`,
      );
    } else {
      lines.push(
        `            COMPREPLY=($(compgen -W '${globalFlags}' -- "$cur"))`,
      );
    }
    if (isBranchCommand || isWorktreeCommand) {
      if (options.length > 0) {
        lines.push('            if [[ "$cur" != -* ]]; then');
        lines.push(
          `                COMPREPLY=($(compgen -W "$(${completionFunction})" -- "$cur"))`,
        );
        lines.push("            fi");
      } else {
        lines.push(
          `            COMPREPLY=($(compgen -W "$(${completionFunction})" -- "$cur"))`,
        );
      }
    }
    lines.push("            ;;");
  }

  for (const command of COMMANDS) {
    if (!command.subcommands) continue;
    const subNames = command.subcommands.map((s) => s.name).join(" ");
    lines.push(`        ${command.name})`);
    lines.push("            if [[ $cword -eq 2 ]]; then");
    lines.push(
      `                COMPREPLY=($(compgen -W '${subNames}' -- "$cur"))`,
    );
    lines.push("            else");
    lines.push('                local subcmd="${COMP_WORDS[2]}"');
    lines.push('                case "$subcmd" in');
    for (const sub of command.subcommands) {
      const subFlags = (sub.options ?? [])
        .flatMap((option) => [
          `--${option.name}`,
          ...(option.short ? [`-${option.short}`] : []),
        ])
        .join(" ");
      const allFlags = subFlags ? `${globalFlags} ${subFlags}` : globalFlags;
      lines.push(`                    ${sub.name})`);
      if (sub.completionType === "path") {
        lines.push('                        if [[ "$cur" != -* ]]; then');
        lines.push(
          '                            COMPREPLY=($(compgen -d -- "$cur"))',
        );
        lines.push("                        else");
        lines.push(
          `                            COMPREPLY=($(compgen -W '${allFlags}' -- "$cur"))`,
        );
        lines.push("                        fi");
      } else {
        lines.push(
          `                        COMPREPLY=($(compgen -W '${allFlags}' -- "$cur"))`,
        );
      }
      lines.push("                        ;;");
    }
    lines.push("                esac");
    lines.push("            fi");
    lines.push("            ;;");
  }

  lines.push("    esac");
  lines.push('    if [[ ${#COMPREPLY[@]} -eq 0 && "$cur" == -* ]]; then');
  lines.push(`        COMPREPLY=($(compgen -W '${globalFlags}' -- "$cur"))`);
  lines.push("    fi");
  lines.push("}");
  lines.push("");
  lines.push("complete -F _wct wct");
  lines.push("");

  return lines.join("\n");
}

function generateZshCompletions(): string {
  const branchCommands = COMMANDS.filter(
    (command) =>
      command.args?.includes("<branch>") &&
      command.completionType !== "worktree",
  ).flatMap((command) => getAllNames(command));
  const worktreeCommands = COMMANDS.filter(
    (command) => command.completionType === "worktree",
  ).flatMap((command) => getAllNames(command));

  const lines: Array<string> = [
    "#compdef wct",
    "# Zsh completions for wct",
    "# Generated by: wct --completions zsh",
    "",
    "_wct_branches() {",
    "    local branches",
    "    branches=($(git branch --format='%(refname:short)' 2>/dev/null))",
    "    _describe 'branch' branches",
    "}",
    "",
    "_wct_worktree_branches() {",
    "    local branches",
    "    branches=($(git worktree list --porcelain 2>/dev/null | sed -n 's|^branch refs/heads/||p'))",
    "    _describe 'branch' branches",
    "}",
    "",
    "_wct_profiles() {",
    "    local profiles",
    "    if [[ -f .wct.yaml ]]; then",
    '        profiles=($(awk \'/^profiles:/{found=1;next} found && /^[^ ]/{exit} found && /^  [a-zA-Z]/{sub(/^  /,"");sub(/:.*/,"");print}\' .wct.yaml))',
    "        _describe 'profile' profiles",
    "    fi",
    "}",
    "",
    "_wct() {",
    "    local -a commands",
    "    commands=(",
  ];

  for (const command of COMMANDS) {
    for (const name of getAllNames(command)) {
      lines.push(`        '${name}:${command.description}'`);
    }
  }
  lines.push("    )");
  lines.push("");
  lines.push("    _arguments -C \\");
  lines.push("        '(-h --help)'{-h,--help}'[Show help information]' \\");
  lines.push("        '--version[Show version information]' \\");
  lines.push(
    "        '--completions[Print shell completion script]:shell:(fish bash zsh sh)' \\",
  );
  lines.push(
    `        '--log-level[Sets the minimum log level]:level:(${GLOBAL_LOG_LEVELS.join(" ")})' \\`,
  );
  lines.push("        '1:command:->command' \\");
  lines.push("        '*::arg:->args'");
  lines.push("");
  lines.push('    case "$state" in');
  lines.push("        command)");
  lines.push("            _describe 'wct command' commands");
  lines.push("            ;;");
  lines.push("        args)");
  lines.push('            case "$words[1]" in');

  for (const command of COMMANDS) {
    if (command.subcommands) {
      lines.push(`                ${command.name})`);
      lines.push("                    if (( CURRENT == 2 )); then");
      lines.push("                        local -a subcmds");
      lines.push("                        subcmds=(");
      for (const sub of command.subcommands) {
        lines.push(
          `                            '${sub.name}:${sub.description}'`,
        );
      }
      lines.push("                        )");
      lines.push(
        `                        _describe '${command.name} subcommand' subcmds`,
      );
      lines.push("                    else");
      lines.push('                        case "$words[2]" in');
      for (const sub of command.subcommands) {
        const hasSubOptions = sub.options && sub.options.length > 0;
        const isPathSub = sub.completionType === "path";
        if (!hasSubOptions && !isPathSub) continue;
        lines.push(`                            ${sub.name})`);
        const argParts: Array<string> = [];
        for (const option of sub.options ?? []) {
          if (option.short) {
            if (option.type === "string") {
              const completionAction = option.completionValues
                ? option.completionValues.replace(/^__/, "_")
                : "";
              argParts.push(
                `                                    '(-${option.short} --${option.name})'{-${option.short},--${option.name}}'[${option.description}]:${option.placeholder || option.name}:${completionAction}'`,
              );
            } else {
              argParts.push(
                `                                    '(-${option.short} --${option.name})'{-${option.short},--${option.name}}'[${option.description}]'`,
              );
            }
          } else if (option.type === "string") {
            const completionAction = option.completionValues
              ? option.completionValues.replace(/^__/, "_")
              : "";
            argParts.push(
              `                                    '--${option.name}[${option.description}]:${option.placeholder || option.name}:${completionAction}'`,
            );
          } else {
            argParts.push(
              `                                    '--${option.name}[${option.description}]'`,
            );
          }
        }
        if (isPathSub) {
          argParts.push(
            "                                    '*:path:_files -/'",
          );
        }
        lines.push(
          `                                _arguments \\\n${argParts.join(" \\\n")}`,
        );
        lines.push("                                ;;");
      }
      lines.push("                        esac");
      lines.push("                    fi");
      lines.push("                    ;;");
    }
  }

  for (const command of COMMANDS) {
    if (command.subcommands) continue;
    const allNames = getAllNames(command);
    const isBranchCommand = allNames.some((name) =>
      branchCommands.includes(name),
    );
    const isWorktreeCommand = allNames.some((name) =>
      worktreeCommands.includes(name),
    );
    const hasOptions = command.options && command.options.length > 0;
    const completionFunction = isWorktreeCommand
      ? "_wct_worktree_branches"
      : "_wct_branches";

    if (!isBranchCommand && !isWorktreeCommand && !hasOptions) continue;

    lines.push(`                ${allNames.join("|")})`);

    if (hasOptions && command.options) {
      lines.push("                    _arguments \\");
      const optionLines: Array<string> = [];
      for (const option of command.options) {
        if (option.short) {
          if (option.type === "string") {
            const completionAction = option.completionValues
              ? option.completionValues.replace(/^__/, "_")
              : "";
            optionLines.push(
              `                        '(-${option.short} --${option.name})'{-${option.short},--${option.name}}'[${option.description}]:${option.placeholder || option.name}:${completionAction}'`,
            );
          } else {
            optionLines.push(
              `                        '(-${option.short} --${option.name})'{-${option.short},--${option.name}}'[${option.description}]'`,
            );
          }
        } else if (option.type === "string") {
          const completionAction = option.completionValues
            ? option.completionValues.replace(/^__/, "_")
            : "";
          optionLines.push(
            `                        '--${option.name}[${option.description}]:${option.placeholder || option.name}:${completionAction}'`,
          );
        } else {
          optionLines.push(
            `                        '--${option.name}[${option.description}]'`,
          );
        }
      }
      if (isBranchCommand || isWorktreeCommand) {
        optionLines.push(
          `                        '*:branch:${completionFunction}'`,
        );
      }
      lines.push(optionLines.join(" \\\n"));
      lines.push("                    ;;");
    } else if (isBranchCommand || isWorktreeCommand) {
      lines.push(`                    ${completionFunction}`);
      lines.push("                    ;;");
    }
  }

  lines.push("            esac");
  lines.push("            ;;");
  lines.push("    esac");
  lines.push("}");
  lines.push("");
  lines.push("compdef _wct wct");
  lines.push("");

  return lines.join("\n");
}

export function generateCompletionScript(
  shell: "fish" | "bash" | "zsh",
): string {
  switch (shell) {
    case "fish":
      return generateFishCompletions();
    case "bash":
      return generateBashCompletions();
    case "zsh":
      return generateZshCompletions();
  }
}

export function getCustomCompletionShell(
  args: ReadonlyArray<string>,
): "fish" | "bash" | "zsh" | null {
  for (let index = 0; index < args.length; index++) {
    const arg = args[index];
    if (arg === undefined) {
      continue;
    }

    if (arg === "--completions") {
      const shell = args[index + 1];
      if (shell === "fish" || shell === "bash" || shell === "zsh") {
        return shell;
      }
      return null;
    }

    if (!arg.startsWith("--completions=")) {
      continue;
    }

    const shell = arg.slice("--completions=".length);
    if (shell === "fish" || shell === "bash" || shell === "zsh") {
      return shell;
    }
    return null;
  }

  return null;
}
